package com.ghtd.view;

import com.ghtd.bean.DanhMucBean;
import com.ghtd.controller.ChuyenManHinhControllerQTV;
import java.util.ArrayList;
import java.util.List;
/**
 *
 * @author Asus
 */
public class MainJFrameQTV extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrameQTV() {
        initComponents();
        
        setTitle("HỆ THỐNG HỖ TRỢ GIAO HÀNG TIỆN ĐƯỜNG");
        
        List<DanhMucBean> listItem = new ArrayList<>();
        listItem.add(new DanhMucBean("AccountEditKhachHang", jPanelQuanLyKhachHang, jLabelQuanLyKhachHang));
        listItem.add(new DanhMucBean("AccountEditNhanVien", jPanelQuanLyNhanVien, jLabelQuanLyNhanVien));
        listItem.add(new DanhMucBean("AllOrderQTV", jPanelAllOrder, jLabelAllOrder));
        
        ChuyenManHinhControllerQTV controller = new ChuyenManHinhControllerQTV(jPanelView);
        controller.setView(jPanelAllOrder, jLabelAllOrder);
        controller.setEvent(listItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAll = new javax.swing.JPanel();
        jPanelOptions = new javax.swing.JPanel();
        jPanelHome = new javax.swing.JPanel();
        jLabelHome = new javax.swing.JLabel();
        jPanelQuanLyKhachHang = new javax.swing.JPanel();
        jLabelQuanLyKhachHang = new javax.swing.JLabel();
        jPanelAllOrder = new javax.swing.JPanel();
        jLabelAllOrder = new javax.swing.JLabel();
        jButtonLogOut = new javax.swing.JButton();
        jPanelQuanLyNhanVien = new javax.swing.JPanel();
        jLabelQuanLyNhanVien = new javax.swing.JLabel();
        jPanelView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelAll.setBackground(new java.awt.Color(255, 255, 255));

        jPanelOptions.setBackground(new java.awt.Color(117, 184, 85));
        jPanelOptions.setPreferredSize(new java.awt.Dimension(384, 649));

        jPanelHome.setBackground(new java.awt.Color(21, 114, 65));

        jLabelHome.setFont(new java.awt.Font("Montserrat", 3, 20)); // NOI18N
        jLabelHome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ghtd/images/truck.png"))); // NOI18N
        jLabelHome.setText("GIAO HÀNG TIỆN ĐƯỜNG");

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHomeLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabelHome)
                .addGap(20, 20, 20))
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelHome, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        jPanelQuanLyKhachHang.setBackground(new java.awt.Color(255, 102, 102));
        jPanelQuanLyKhachHang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 246, 244), 5));

        jLabelQuanLyKhachHang.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabelQuanLyKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ghtd/images/manageaccount.png"))); // NOI18N
        jLabelQuanLyKhachHang.setText("QUẢN LÝ KHÁCH HÀNG");

        javax.swing.GroupLayout jPanelQuanLyKhachHangLayout = new javax.swing.GroupLayout(jPanelQuanLyKhachHang);
        jPanelQuanLyKhachHang.setLayout(jPanelQuanLyKhachHangLayout);
        jPanelQuanLyKhachHangLayout.setHorizontalGroup(
            jPanelQuanLyKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelQuanLyKhachHangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelQuanLyKhachHang)
                .addGap(40, 40, 40))
        );
        jPanelQuanLyKhachHangLayout.setVerticalGroup(
            jPanelQuanLyKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuanLyKhachHangLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelQuanLyKhachHang)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanelAllOrder.setBackground(new java.awt.Color(255, 102, 102));
        jPanelAllOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 246, 244), 5));

        jLabelAllOrder.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabelAllOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ghtd/images/description.png"))); // NOI18N
        jLabelAllOrder.setText("TẤT CẢ ĐƠN HÀNG");

        javax.swing.GroupLayout jPanelAllOrderLayout = new javax.swing.GroupLayout(jPanelAllOrder);
        jPanelAllOrder.setLayout(jPanelAllOrderLayout);
        jPanelAllOrderLayout.setHorizontalGroup(
            jPanelAllOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAllOrderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelAllOrder)
                .addGap(64, 64, 64))
        );
        jPanelAllOrderLayout.setVerticalGroup(
            jPanelAllOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAllOrderLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelAllOrder)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jButtonLogOut.setBackground(new java.awt.Color(255, 102, 102));
        jButtonLogOut.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jButtonLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ghtd/images/logout.png"))); // NOI18N
        jButtonLogOut.setText("ĐĂNG XUẤT");
        jButtonLogOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        jPanelQuanLyNhanVien.setBackground(new java.awt.Color(255, 102, 102));
        jPanelQuanLyNhanVien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 246, 244), 5));

        jLabelQuanLyNhanVien.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabelQuanLyNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ghtd/images/manageaccount.png"))); // NOI18N
        jLabelQuanLyNhanVien.setText("QUẢN LÝ NHÂN VIÊN");

        javax.swing.GroupLayout jPanelQuanLyNhanVienLayout = new javax.swing.GroupLayout(jPanelQuanLyNhanVien);
        jPanelQuanLyNhanVien.setLayout(jPanelQuanLyNhanVienLayout);
        jPanelQuanLyNhanVienLayout.setHorizontalGroup(
            jPanelQuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuanLyNhanVienLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabelQuanLyNhanVien)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelQuanLyNhanVienLayout.setVerticalGroup(
            jPanelQuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuanLyNhanVienLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelQuanLyNhanVien)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelOptionsLayout = new javax.swing.GroupLayout(jPanelOptions);
        jPanelOptions.setLayout(jPanelOptionsLayout);
        jPanelOptionsLayout.setHorizontalGroup(
            jPanelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelQuanLyKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelAllOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelQuanLyNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanelOptionsLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jButtonLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelOptionsLayout.setVerticalGroup(
            jPanelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOptionsLayout.createSequentialGroup()
                .addComponent(jPanelHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelQuanLyKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelQuanLyNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelAllOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jPanelView.setBackground(new java.awt.Color(173, 56, 56));

        javax.swing.GroupLayout jPanelViewLayout = new javax.swing.GroupLayout(jPanelView);
        jPanelView.setLayout(jPanelViewLayout);
        jPanelViewLayout.setHorizontalGroup(
            jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 956, Short.MAX_VALUE)
        );
        jPanelViewLayout.setVerticalGroup(
            jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelAllLayout = new javax.swing.GroupLayout(jPanelAll);
        jPanelAll.setLayout(jPanelAllLayout);
        jPanelAllLayout.setHorizontalGroup(
            jPanelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAllLayout.createSequentialGroup()
                .addComponent(jPanelOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAllLayout.setVerticalGroup(
            jPanelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelOptions, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
            .addComponent(jPanelView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogOut;
    private javax.swing.JLabel jLabelAllOrder;
    private javax.swing.JLabel jLabelHome;
    private javax.swing.JLabel jLabelQuanLyKhachHang;
    private javax.swing.JLabel jLabelQuanLyNhanVien;
    private javax.swing.JPanel jPanelAll;
    private javax.swing.JPanel jPanelAllOrder;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelOptions;
    private javax.swing.JPanel jPanelQuanLyKhachHang;
    private javax.swing.JPanel jPanelQuanLyNhanVien;
    private javax.swing.JPanel jPanelView;
    // End of variables declaration//GEN-END:variables
}
